/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:d8259c0f-0973-465c-b03d-930bd0106e79",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_96HXwKP99",
    "aws_user_pools_web_client_id": "7fqvb9qe2405l9s79c08b528ig",
    "oauth": {}
};


export default awsmobile;
